# Generated by Django 5.1.3 on 2026-06-13 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название тарифа')),
                ('type', models.CharField(choices=[('single', 'Разовое посещение'), ('daily', 'Дневной'), ('monthly', 'Месячный'), ('unlimited', 'Безлимитный')], max_length=16, verbose_name='Тип')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, ₽')),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Сколько дней действует абонемент после покупки', verbose_name='Срок действия, дней')),
                ('hours_per_day', models.PositiveIntegerField(default=8, help_text='Максимум часов бронирования в сутки по этому тарифу', verbose_name='Часов в сутки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для покупки')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('expired', 'Истёк'), ('cancelled', 'Отменён')], default='active', max_length=16, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.tariff', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
