# Generated by Django 5.1.3 on 2026-04-24 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=128, verbose_name='Название тарифа')),
                ('tip', models.CharField(choices=[('razovyj', 'Разовое посещение'), ('dnevnoj', 'Дневной'), ('mesyachnyj', 'Месячный'), ('bezlimitnyj', 'Безлимитный')], max_length=16, verbose_name='Тип')),
                ('opisanie', models.TextField(blank=True, verbose_name='Описание')),
                ('tsena', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена, ₽')),
                ('srok_dnej', models.PositiveIntegerField(default=1, help_text='Сколько дней действует абонемент после покупки', verbose_name='Срок действия, дней')),
                ('chasov_v_sutki', models.PositiveIntegerField(default=8, help_text='Максимум часов бронирования в сутки по этому тарифу', verbose_name='Часов в сутки')),
                ('aktiven', models.BooleanField(default=True, verbose_name='Доступен для покупки')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['tsena'],
            },
        ),
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pokupki', models.DateTimeField(auto_now_add=True, verbose_name='Дата покупки')),
                ('data_nachala', models.DateField(verbose_name='Дата начала')),
                ('data_okonchaniya', models.DateField(verbose_name='Дата окончания')),
                ('status', models.CharField(choices=[('aktiven', 'Активен'), ('istek', 'Истёк'), ('otmenen', 'Отменён')], default='aktiven', max_length=16, verbose_name='Статус')),
                ('polzovatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonementy', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('tarif', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='abonementy', to='subscriptions.tarif', verbose_name='Тариф')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['-data_pokupki'],
            },
        ),
    ]
