# Generated by Django 5.1.3 on 2026-04-24 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bronirovanie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Дата')),
                ('vremya_nachala', models.TimeField(verbose_name='Время начала')),
                ('vremya_okonchaniya', models.TimeField(verbose_name='Время окончания')),
                ('kommentarij', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('ozhidanie', 'Ожидает подтверждения'), ('podtverzhdeno', 'Подтверждено'), ('otmeneno', 'Отменено'), ('zaversheno', 'Завершено')], default='podtverzhdeno', max_length=16, verbose_name='Статус')),
                ('data_sozdaniya', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('polzovatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bronirovaniya', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('resurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bronirovaniya', to='resources.resurs', verbose_name='Ресурс')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-data', '-vremya_nachala'],
                'indexes': [models.Index(fields=['resurs', 'data'], name='bookings_br_resurs__dd9f9a_idx')],
            },
        ),
    ]
