# Generated by Django 5.1.3 on 2026-06-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название')),
                ('type', models.CharField(choices=[('open_seat', 'Открытое рабочее место'), ('fixed_desk', 'Фиксированный стол'), ('private_office', 'Приватный кабинет'), ('meeting_room', 'Переговорная комната')], max_length=32, verbose_name='Тип ресурса')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('capacity', models.PositiveIntegerField(default=1, verbose_name='Вместимость (чел.)')),
                ('price_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за час, ₽')),
                ('equipment', models.CharField(blank=True, help_text='Перечислите через запятую: проектор, флипчарт, монитор и т.д.', max_length=255, verbose_name='Оборудование')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='resources/', verbose_name='Фотография')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступен для бронирования')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'ordering': ['type', 'name'],
            },
        ),
    ]
