# Generated by Django 5.1.3 on 2026-04-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazvanie', models.CharField(max_length=128, verbose_name='Название')),
                ('tip', models.CharField(choices=[('otkrytoe', 'Открытое рабочее место'), ('fiksirovannyj', 'Фиксированный стол'), ('privatnyj', 'Приватный кабинет'), ('peregovornaya', 'Переговорная комната')], max_length=32, verbose_name='Тип ресурса')),
                ('opisanie', models.TextField(blank=True, verbose_name='Описание')),
                ('vmestimost', models.PositiveIntegerField(default=1, verbose_name='Вместимость (чел.)')),
                ('tsena_za_chas', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена за час, ₽')),
                ('oborudovanie', models.CharField(blank=True, help_text='Перечислите через запятую: проектор, флипчарт, монитор и т.д.', max_length=255, verbose_name='Оборудование')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='resursy/', verbose_name='Фотография')),
                ('aktiven', models.BooleanField(default=True, verbose_name='Доступен для бронирования')),
                ('data_sozdaniya', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'ordering': ['tip', 'nazvanie'],
            },
        ),
    ]
